# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Test

on:
  push:
    branches: [ "development", "development_actions_test" ]
  pull_request:
    branches: [ "master", "development", "development_actions_test"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore -s ./MageNet.API -s ./MageNet.Persistence -s ./MageNet.Services -s ./MageNet.UnitTesting -s ./MageNet.IntegrationTesting
      - name: Build
        run: dotnet build ./MageNet.sln --no-restore
      - name: Test
        run: dotnet test ./MageNet.sln --no-build --verbosity normal
