name: .NET Create App Container

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]


jobs:
  build_and_upload:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ./MageNet.API/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: "magenet:latest"
          load: true

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "magenet:latest"